# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
registries:
  azure-npm:
    type: npm-registry
    url: https://pkgs.dev.azure.com/agilysys/Stay/_packaging/PMS/npm/registry
    username: agilysys
    password: ${{ secrets.AZDO_PMS_FEED_TOKEN }}
updates:
  - package-ecosystem: "npm"
    registries:
      - azure-npm
    target-branch: "develop"
    directory: "/"
    schedule:
      interval: "weekly"