version: 2
registries:
  azure-npm:
    type: npm-registry
    url: "" 
    username: navinkumar
    password: ${{ secrets.AZDO_PMS_FEED_TOKEN }}
updates:
  - package-ecosystem: "npm"
    registries:
      - azure-npm
    target-branch: "develop"
    directory: "/"
    schedule:
      interval: "weekly"