name: Checks

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
    branches: [develop, main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  checks:
    name: Run checks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          git config --global user.name 'anthroponymy'
          git config --global user.email 'ksnavinkumar.diary@gmail.com'
          npm ci
          npm run build-all

      - name: Run tests of all packages
        run: npm run test-all