name: Prerelease

on:
  workflow_dispatch:
    inputs:
      all:
        description: Run for all
        default: false
        type: boolean
  push:
    branches: [develop]
    paths: ["apps/**", "modules/**"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  changes:
    name: Detect
    uses: ./.github/workflows/changes.yml
    secrets: inherit
    with:
      all: ${{ inputs.all || false }}

  versions:
    name: Versions
    needs:
      - changes
    if: ${{ needs.changes.outputs.all-json != '[]' && needs.changes.outputs.all-json != '' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - name: Setup Git User
        uses: navinkumar-inc/stay-github-actions/setup-git@main

      - name: Setup NPM
        uses: navinkumar-inc/stay-github-actions/setup-nodejs@main
        with:
          token: ${{ secrets.AZDO_PMS_FEED_TOKEN }}
          node-version: 20

      - name: Prerelease version
        run: npm run prerelease-version

  publish:
    name: Publish modules
    needs:
      - changes
      - versions
    if: ${{ always() && needs.changes.outputs.all-json != '[]' && needs.changes.outputs.all-json != '' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
        with:
          ref: ${{ github.ref_name }}
          fetch-depth: 0

      - name: Setup Git User
        uses: navinkumar-inc/stay-github-actions/setup-git@main

      - name: Setup NPM
        uses: navinkumar-inc/stay-github-actions/setup-nodejs@main
        with:
          token: ${{ secrets.AZDO_PMS_FEED_TOKEN }}
          node-version: 20

      - name: Install dependencies
        run: |
          npm ci
          npm run build-all

      - name: Run tests of all packages
        run: |
          npm run test-all

      - name: Publish to NPM
        run: |
          npm run publish

  docker:
    name: Build docker images
    needs:
      - changes
      - publish
    if: ${{ always() && needs.changes.outputs.docker-json != '[]' && needs.changes.outputs.docker-json != '' }}
    uses: ./.github/workflows/docker.yml
    with:
      docker-json: ${{ needs.changes.outputs.docker-json }}
    secrets: inherit